#!/usr/bin/env bash

#
#  Aurtool V1.0.1
#
#  Maintainer: Eris Nihila (M1ndFlay3r)
#              sp0t1fyfr33tr1alabus3@outlook.com
#
# This software comes with absolutely NO WARRANTY, expressed or implied. Any and all use of this software is entirely
# at your own risk. By using this software you agree to release and forever discharge the developer from all manner of actions,
# cause of action, debts, accounts, bonds, contracts, claims and demands for or by any reason of damage, loss (including data loss)
# or injury to person or property that has been or may be sustained as a result of your usage of this software.
#
# This software is shipped under the GNU General Public License and is provided "as is", with no explicit or implied expectation or
# obligation to provide support, development, or otherwise unspecified services of any kind. Furthermore, the developer reserves the
# right to cease development at any time for any reason, with no obligation to provide reason(s) for cessation.
#
#
#


### initialization steps
###
OP=$1
OPINPUT="${@:2}"
USR="$(whoami)"
STARTDIR=$(pwd)
PATH=$STARTDIR/${BASH_SOURCE%/*}:$PATH
LIBDEFLOC=/usr/include/libaurtool
if [ -f "$LIBDEFLOC" ]; then
  source /usr/include/libaurtool
else
  source ${BASH_SOURCE%/*}/resources/libaurtool
fi
GOAHEAD="0"
if [ -z "$NCHECKALL" ]; then
  NCHECKALL="0"
fi
###

###
### env normalization 
###
PATH=/usr/bin:$PATH
if which gcc &> /dev/null; then
  CC='gcc'
  CXX='g++'
fi

### check run conditions
###
if [ "$USR" == root ]; then
  ctext red std "Error: aurtool cannot be run as root!"
  exit 13
fi

VALID=("-S" "-Sy" "-Syu" "-Ss" "--help" "-Syyu" "-Sss" "--version" "-SS" "-R")
if [ ! -z "$OP" ]; then
  if ! isvalidoperation "$1" ${VALID[@]}; then
    ctext red nnl "Error: "
    ctext magenta nnl "$1"
    ctext red std ": Invalid command!"
    ctext cyan std "Do aurtool --help for help page"
    exit 22
  fi
else
  ctext red std "Error: aurtool requires input!"
  ctext cyan std "Do aurtool --help for help page"
  exit 22
fi

if ! which package-query &> /dev/null; then
  if [ -z "$PKGQUERYINS" ]; then
    PKGQUERYINS="0"
  fi
  if [ ! $PKGQUERYINS == 1 ]; then
    ctext magenta std "Error: package-query not found in PATH!"
    if ! isyes "$(ctext cyan nnl "Install it now? (Y/n)")"; then
      exit 65
    else
      PKGQUERYINS="1" NCHECKALL="1" aurtool -SS package-query
    fi
  fi
fi

function OPERROR {
  if [ -z "$OPINPUT" ]; then
    ctext red std "Error: $OP requires additional input."
    ctext cyan std "Do aurtool --help for help page"
    exit 22
  fi
}

if [ -z "$SILENT" ]; then
  SILENT=0
elif [ $SILENT = 1 ]; then
  NODEL=1
  NCHECKALL=1
fi

###


### Script functionality begins here.
### Yes, I wrote the functions as if statements.
### No, it does not have any effects on functionality.
### No, I don't know why I did that. I was high. Get off my back.
###
if [ "$OP" == -Sss ]; then
  OPERROR
  package-query -A -s ${@:2}
fi

if [ "$OP" == -Ss ]; then
  OPERROR
  ctext cyan std "---------"
  ctext cyan std " Non-AUR "
  ctext cyan std "---------"
  pacsearch ${@:2}
  ctext cyan std "---------"
  ctext cyan std "   AUR   "
  ctext cyan std "---------"
  package-query -A -s ${@:2}
fi

if [ "$OP" == -SS ]; then
  OPERROR
  if [ $NCHECKALL == 0 ]; then
    echo " "
    for dD in ${@:2}; do
      ctext blue nnl " $dD"
    done
    echo " "
    echo " "
    if isyes "$(ctext cyan nnl "Install these packages? (Y/n)")"; then
      GOAHEAD="1"
    else
      GOAHEAD="0"
    fi
  else
      GOAHEAD="1"
      NCHECKALL="0"
  fi
  if [ $GOAHEAD == "1" ]; then
    for b in ${@:2}; do
      cd $HOME
      mkdir .aurtool
      cd .aurtool
      if [ $b == dxvk-mingw-git ]; then
        b="dxvk-git"
      elif [ $b == openrazer-daemon ] || [ $b == openrazer-driver-dkms ] || [ $b == openrazer-meta ] || [ $b == python-openrazer ]; then
        b="openrazer"
      fi
      git clone http://aur.archlinux.org/$b.git
      cd $b
      PKGB=./PKGBUILD
      if [ ! -f $PKGB ]; then
        ctext red std "Error: package does not exist by the name $b!"
        ctext magenta std "Aborting"
        cd $HOME
        exit 6
      fi
      #
      # Yes, this is a pointless function that uses up 3 lines unnecessarily. The script didn't behave properly without it. Bash has moods, and Brian Fox hates us all.
      #
      function PKGBUILD {
      if DEFINVERT="1" isyes "$(ctext cyan nnl "Would you like to edit the PKGBUILD? (y/N)")"; then
        BINDIRS=(
          '/bin/'
          '/sbin/'
          '/usr/bin/'
          '/usr/sbin/'
          '/usr/local/bin/'
          '/usr/local/sbin/'
        )
        TEHNEWSFLAG="0"
        TAHNOOSFLABG="0"
        unset KNOWNEDITDIR
        for i in ${BINDIRS[@]}; do
          if ls -a $i/nano &> /dev/null; then
            TEHNEWSFLAG=1
            KNOWNEDITDIR="$i/nano"
            break
          elif ls -a $i/nvim &> /dev/null; then
            TAHNOOSFLABG=1
            KNOWNEDITDIR="$i/nvim"
            break
          elif ls -a $i/vim &> /dev/null; then
            TAHNOOSFLABG=1
            KNOWNEDITDIR="$i/vim"
            break
          elif ls -a $i/vi &> /dev/null; then
            TAHNOOSFLABG=1
            KNOWNEDITDIR="$i/vi"
            break
          fi
        done
        if [ -z "$KNOWNEDITDIR" ]; then
          if which nano &> /dev/null; then
            KNOWNEDITDIR="$(which nano)"
          elif which nvim &> /dev/null; then
            KNOWNEDITDIR="$(which nvim)"
          elif which vim &> /dev/null; then
            KNOWNEDITDIR="$(which vim)"
          elif which vi &> /dev/null; then
            KNOWNEDITDIR="$(which vi)"
          fi
        fi
        if [ ! -z "$KNOWNEDITDIR" ]; then
          eval $KNOWNEDITDIR ./PKGBUILD
        elif ls -a /home/$USER/.aurtool_edit_command &> /dev/null; then
          KNOWNEDITDIR="$(cat /home/$USER/.aurtool_edit_command)"
          eval $KNOWNEDITDIR ./PKGBUILD
        else
          ctext magenta std "No suitable text editor found!"
          ctext cyan nnl "If one is present on the system, enter its command now (eg: nano, vim, emacs, etc). Otherwise leave blank to skip PKGBUILD editing: "
          read PKGEDIT
          if [ -z "$PKGEDIT" ]; then
            PKGEDIT="true"
            ctext magenta std "Editor does not exist! skipping PKGBUILD editing for this session"
          fi
          if [ -v $PKGEDIT ]; then
            $PKGEDIT ./PKGBUILD
          fi
        fi
      fi
      }
      PKGBUILD
      unset makedepends
      unset optdepends
      unset depends
      source ./PKGBUILD
      uDEPS=(${makedepends[@]} ${depends[@]})
      for i in ${uDEPS[@]}; do
        i=${i%=*}
        i=${i%>*}
        i=${i%<*}
        DEPS=(${DEPS[@]} $i)
      done
      for i in ${DEPS[@]}; do
        if ! pacman -Ql $i &> /dev/null; then
          ctext cyan std "Trying to install $i with pacman (dependency)"
          if ! sudo pacman -S --noconfirm --needed $i; then
            ctext magenta std "Installing $i with pacman failed"
            ctext cyan std "Trying to install $i from AUR"
            if ! NODEL="1" NCHECKALL="1" aurtool -SS $i; then
              ctext red std "FATAL: Unable to install dependency $i!"
              cd $HOME
              exit 65
            fi
          fi
        fi
      done
      if ! makepkg -csi || false; then
        ctext red std "Error! Aborting"
        cd $HOME
        exit 131
      fi
      cd $HOME/.aurtool
    done
    if [ -z "$NODEL" ]; then
      NODEL="0"
    fi
    if [ ! "$NODEL" == 1 ]; then
      if isyes "$(ctext cyan nnl "Build files and / or built packages are stored in .aurtool in your home directory. Would you like to delete them? (Y/n)")"; then
        echo "Cleaning up.."
        cd $HOME
        rm -rf $HOME/.aurtool
      fi
    fi
  else
    echo "Aborting"
    cd $HOME
    exit 125
  fi
fi

if [ "$OP" == -Syy ]; then
  UPD=$(package-query -A -u)
  if [ -z "$UPD" ]; then
    ctext cyan std "No AUR package updates available"
    exit 0
  else
    echo " "
    ctext blue std "$UPD"
    echo " "
  fi
fi

if [ "$OP" == -Syyu ]; then
  UPD=$(package-query -A -u | grep -oP "aur/\K[^ ]*")
  if [ -z "$UPD" ]; then
    echo " there is nothing to do"
    exit 0
  fi
  echo " "
  for vV in $UPD; do
    ctext blue nnl " $vV"
  done
  echo " "
  echo " "
  if isyes "$(ctext cyan nnl "Update these AUR packages? (Y/n)")"; then
    for i in $UPD; do
      if [ $SILENT != 1 ]; then
        NCHECKALL="1" aurtool -SS $i
      else
        NCHECKALL="1" NODEL="1" SILENT="1" aurtool -SS $i
      fi
    done
  else
    echo "Aborting"
    cd $HOME
    exit 125
  fi
fi

if [ "$OP" == -Syu ]; then
  ctext cyan std "Updating non-AUR packages..."
  sudo pacman -Syu
  ctext cyan std "Updating AUR packages..."
  if [ $SILENT == 1 ]; then
    SILENT=1 aurtool -Syyu
  else
    aurtool -Syyu
  fi
fi

if [ "$OP" == -S ]; then
  OPERROR
  echo " "
  for dD in ${@:2}; do
    ctext blue nnl " $dD"
  done
  echo " "
  echo " "
  if isyes "$(ctext cyan nnl "Install these packages? (Y/n)")"; then
    for m in ${@:2}; do
      ctext cyan std "Trying to install $m using pacman..."
      if ! sudo pacman -S --needed --noconfirm $m; then
        ctext magenta std "Installing $m using pacman failed!"
        ctext cyan std "Trying to install $m using AUR..."
        if [ $SILENT != 1 ]; then
          NCHECKALL="1" aurtool -SS $m
        else
          NODEL=1 NCHECKALL="1" SILENT=1 aurtool -SS $m
        fi
      fi
    done
  else
    echo "Aborting"
    cd $HOME
    exit 125
  fi
fi

if [ "$OP" == -R ]; then
  OPERROR
  echo " "
  for dD in ${@:2}; do
    ctext blue nnl " $dD"
  done
  echo " "
  echo " "
  if isyes "$(ctext cyan nnl "Remove these packages? (Y/n)")"; then
    for u in ${@:2}; do
      sudo pacman -R --noconfirm $u
    done
  else
    ctext magenta std "Aborting"
    cd $HOME
    exit 125
  fi
fi

if [ "$OP" == --version ]; then
  ctext green std "aurtool V1.0 RC2"
fi

if [ "$OP" == --help ]; then
  ctext white std " $(tput bold)--------------------------------------------------------------------------------------"
  ctext green std " $(tput bold)                   aurtool $(ctext white)-$(ctext cyan) minimal AUR package management system                   "
  ctext white std " $(tput bold)--------------------------------------------------------------------------------------"
  ctext green std "    $(tput bold)options$(ctext white):                                                                             "
  ctext white std "    $(tput bold)--------                                                                             "
  ctext cyan std "       $(tput bold)$(ctext magenta)-SS $(ctext white)         -   install an AUR package (or update a single AUR package).             "
  ctext cyan std "       $(tput bold)$(ctext magenta)-S $(ctext white)          -   install a package, trying pacman first, and AUR if pacman fails      "
  ctext cyan std "       $(tput bold)$(ctext magenta)-Sy $(ctext white)         -   check for updates to installed AUR packages                          "
  ctext cyan std "       $(tput bold)$(ctext magenta)-Syyu  $(ctext white)      -   install all available updates to AUR packages                        "
  ctext cyan std "       $(tput bold)$(ctext magenta)-Syu  $(ctext white)       -   install all available updates to both AUR and non-AUR packages       "
  ctext cyan std "       $(tput bold)$(ctext magenta)-Sss $(ctext white)        -   search the AUR for a package by name                                 "
  ctext cyan std "       $(tput bold)$(ctext magenta)-Ss $(ctext white)         -   search both repositories and AUR for package by name                 "
  ctext cyan std "       $(tput bold)$(ctext magenta)-R $(ctext white)          -   remove a package                                                     "
  ctext cyan std "       $(tput bold)$(ctext magenta)--help $(ctext white)      -   display this help dialog                                             "
  ctext cyan std "       $(tput bold)$(ctext magenta)--version $(ctext white)   -   display aurtool version info                                         "
  echo ""
  ctext white std " $(tput bold)--------------------------------------------------------------------------------------"
  ctext green std "             $(tput bold)               environment flags                                          "
  echo ""
  ctext cyan std "    $(tput bold)   $(ctext yellow)NCHECKALL=1 $(ctext white)-$(ctext cyan) disable PKGBUILD edit prompt and \"are you sure\" prompts           "
  ctext cyan std "    $(tput bold)   $(ctext yellow)    NODEL=1 $(ctext white)-$(ctext cyan) disable prompting user to delete built package after installation   "
  ctext cyan std "    $(tput bold)   $(ctext yellow)   SILENT=1 $(ctext white)-$(ctext cyan) enable both of the above                                            "
  echo ""
  ctext blue std "            $(tput bold)    $(ctext green)ex$(ctext white) -$(ctext blue) SILENT=1 aurtool -S wine-staging-git                                      "
  ctext white std " $(tput bold)--------------------------------------------------------------------------------------"
fi
###
