#!/usr/bin/env bash

function ctext {
  # Set colour from $1
  if [ "$1" == black ]; then
    tput setaf 0
  fi
  if [ "$1" == red ]; then
    tput setaf 1
  fi
  if [ "$1" == green ]; then
    tput setaf 2
  fi
  if [ "$1" == yellow ]; then
    tput setaf 3
  fi
  if [ "$1" == blue ]; then
    tput setaf 4
  fi
  if [ "$1" == magenta ]; then
    tput setaf 5
  fi
  if [ "$1" == cyan ]; then
    tput setaf 6
  fi
  if [ "$1" == white ]; then
    tput setaf 7
  fi
  # Set background colour from $1
  if [ "$1" == dblack ]; then
    tput setab 0
  fi
  if [ "$1" == dred ]; then
    tput setab 1
  fi
  if [ "$1" == dgreen ]; then
    tput setab 2
  fi
  if [ "$1" == dyellow ]; then
    tput setab 3
  fi
  if [ "$1" == dblue ]; then
    tput setab 4
  fi
  if [ "$1" == dmagenta ]; then
    tput setab 5
  fi
  if [ "$1" == dcyan ]; then
    tput setab 6
  fi
  if [ "$1" == dwhite ]; then
    tput setab 7
  fi
  if [ "$1" == reset ]; then
    tput sgr 0
  fi
  # text method from $2
  if [ "$2" == std ]; then
    echo "${@:3}"
    tput sgr 0
  fi
  if [ "$2" == nnl ]; then
    echo -n "${@:3}"
    tput sgr 0
  fi
  if [ "$2" == std,nres ]; then
    echo "${@:3}"
  fi
  if [ "$2" == nnl,nres ]; then
    echo -n "${@:3}"
  fi
}

function isyes {
  if [ ! -z "$1" ]; then
    read -p "$1  " ANSWER
  else
    read ANSWER
  fi
  if [ -z "$ANSWER" ]; then
    if [ -z "$DEFINVERT" ]; then
      ANSWER="y"
    else
      ANSWER="n"
      unset DEFINVERT
    fi
  fi
  if [ $ANSWER == y ] || [ $ANSWER == Y ] || [ $ANSWER == yes ] || [ $ANSWER == Yes ] || [ $ANSWER == YES ]; then
    yes=0 && return 0
  else
    yes=1 && return 1
  fi
}

function isvalidoperation {
  for i in ${@:2}; do
    if [ $1 == $i ]; then
      true
      break
    else
      false
    fi
  done
}
